# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'Ryan Kozak'
tagline:          'hacking, web development, $other'
description:      'hacking, web development, $other'
url:               https://ryankozak.com
baseurl:          

author:
  name:           'Ryan Kozak'
  url:            https://ryankozak.com


# Collections
collections:
  books:
    output: true
    #output_ext: .html
    permalink: /books/:path/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-seo
  - jekyll-seo-tag


# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo: https://github.com/d0n601

stackoverflow:
  link: https://stackoverflow.com/users/4681506/ryan-kozak

disqus:
  shortname: https-ryankozak-com

google_analytics: UA-59830293-1

#Jekyll-Photo-Gallery Settings
exiftag:
 sources:
   - images/photography #Set to location of photos

#MiniMagick
#https://github.com/zroger/jekyll-minimagick
mini_magick:
    photography:
        source: images/photography
        destination: images/photography/thumbnails
        resize: "1280x720"
    headers:
        source: images/headers
        destination: images/headers/thumbnails
        resize: "400x250"

autopages:
  enabled: true
  collections:
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true  # Causes B+W tag to show up as it is written on the terry-pratchet-diary-2017.md page and not lowercase
    
  
# This site uses the pretty permalink structure, this renders all urls with a slash / at the end and 
# no file endings, I guess that is considered pretty :)
permalink: pretty

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page:num/'
  title: ':title | Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
 # extension: htm
 # indexpage: 'default'
  trail: 
    before: 2
    after: 2
